/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cdo.avro.protocol;

@SuppressWarnings("all")
/** avro cdo rpc  */
@org.apache.avro.specific.AvroGenerated
public interface AvroCDOProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroCDOProtocol\",\"namespace\":\"com.cdo.avro.protocol\",\"doc\":\"avro cdo rpc \",\"types\":[{\"type\":\"record\",\"name\":\"AvroCDO\",\"fields\":[{\"name\":\"callId\",\"type\":\"int\"},{\"name\":\"fields\",\"type\":{\"type\":\"map\",\"values\":\"bytes\"}}]}],\"messages\":{\"handleTrans\":{\"request\":[{\"name\":\"avroCDOReq\",\"type\":\"AvroCDO\"}],\"response\":\"AvroCDO\"}}}");
  /**
   */
  com.cdo.avro.protocol.AvroCDO handleTrans(com.cdo.avro.protocol.AvroCDO avroCDOReq) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** avro cdo rpc  */
  public interface Callback extends AvroCDOProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.cdo.avro.protocol.AvroCDOProtocol.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void handleTrans(com.cdo.avro.protocol.AvroCDO avroCDOReq, org.apache.avro.ipc.Callback<com.cdo.avro.protocol.AvroCDO> callback) throws java.io.IOException;
  }
}