/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cdo.avro.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroCDO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2471577526191504831L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroCDO\",\"namespace\":\"com.cdo.avro.schema\",\"fields\":[{\"name\":\"key\",\"type\":[\"null\",{\"type\":\"map\",\"values\":[\"boolean\",\"int\",\"long\",\"float\",\"double\",\"bytes\",\"string\",{\"type\":\"array\",\"items\":\"string\"}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Object> key;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroCDO() {}

  /**
   * All-args constructor.
   * @param key The new value for key
   */
  public AvroCDO(java.util.Map<java.lang.CharSequence,java.lang.Object> key) {
    this.key = key;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.util.Map<java.lang.CharSequence,java.lang.Object>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'key' field.
   * @return The value of the 'key' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Object> getKey() {
    return key;
  }

  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.util.Map<java.lang.CharSequence,java.lang.Object> value) {
    this.key = value;
  }

  /**
   * Creates a new AvroCDO RecordBuilder.
   * @return A new AvroCDO RecordBuilder
   */
  public static com.cdo.avro.schema.AvroCDO.Builder newBuilder() {
    return new com.cdo.avro.schema.AvroCDO.Builder();
  }

  /**
   * Creates a new AvroCDO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroCDO RecordBuilder
   */
  public static com.cdo.avro.schema.AvroCDO.Builder newBuilder(com.cdo.avro.schema.AvroCDO.Builder other) {
    return new com.cdo.avro.schema.AvroCDO.Builder(other);
  }

  /**
   * Creates a new AvroCDO RecordBuilder by copying an existing AvroCDO instance.
   * @param other The existing instance to copy.
   * @return A new AvroCDO RecordBuilder
   */
  public static com.cdo.avro.schema.AvroCDO.Builder newBuilder(com.cdo.avro.schema.AvroCDO other) {
    return new com.cdo.avro.schema.AvroCDO.Builder(other);
  }

  /**
   * RecordBuilder for AvroCDO instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroCDO>
    implements org.apache.avro.data.RecordBuilder<AvroCDO> {

    private java.util.Map<java.lang.CharSequence,java.lang.Object> key;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cdo.avro.schema.AvroCDO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroCDO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cdo.avro.schema.AvroCDO other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'key' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.Object> getKey() {
      return key;
    }

    /**
      * Sets the value of the 'key' field.
      * @param value The value of 'key'.
      * @return This builder.
      */
    public com.cdo.avro.schema.AvroCDO.Builder setKey(java.util.Map<java.lang.CharSequence,java.lang.Object> value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'key' field has been set.
      * @return True if the 'key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'key' field.
      * @return This builder.
      */
    public com.cdo.avro.schema.AvroCDO.Builder clearKey() {
      key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroCDO build() {
      try {
        AvroCDO record = new AvroCDO();
        record.key = fieldSetFlags()[0] ? this.key : (java.util.Map<java.lang.CharSequence,java.lang.Object>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
