// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CDO.proto

package com.cdo.google.protocol;

public final class GoogleCDO {
  private GoogleCDO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CDOProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional sint32 level = 1;
    /**
     * <code>optional sint32 level = 1;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional sint32 level = 1;</code>
     */
    int getLevel();

    // repeated .CDOProto.Entry fields = 2;
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> 
        getFieldsList();
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getFields(int index);
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    java.util.List<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
        getFieldsOrBuilderList();
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder getFieldsOrBuilder(
        int index);

    // optional bytes clientId = 3;
    /**
     * <code>optional bytes clientId = 3;</code>
     *
     * <pre>
     * Globally unique client ID 
     * </pre>
     */
    boolean hasClientId();
    /**
     * <code>optional bytes clientId = 3;</code>
     *
     * <pre>
     * Globally unique client ID 
     * </pre>
     */
    com.google.protobuf.ByteString getClientId();

    // optional sint32 callId = 4;
    /**
     * <code>optional sint32 callId = 4;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    boolean hasCallId();
    /**
     * <code>optional sint32 callId = 4;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    int getCallId();
  }
  /**
   * Protobuf type {@code CDOProto}
   */
  public static final class CDOProto extends
      com.google.protobuf.GeneratedMessage
      implements CDOProtoOrBuilder {
    // Use CDOProto.newBuilder() to construct.
    private CDOProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CDOProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CDOProto defaultInstance;
    public static CDOProto getDefaultInstance() {
      return defaultInstance;
    }

    public CDOProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CDOProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              level_ = input.readSInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                fields_ = new java.util.ArrayList<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry>();
                mutable_bitField0_ |= 0x00000002;
              }
              fields_.add(input.readMessage(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              callId_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cdo.google.protocol.GoogleCDO.CDOProto.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CDOProto> PARSER =
        new com.google.protobuf.AbstractParser<CDOProto>() {
      public CDOProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CDOProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CDOProto> getParserForType() {
      return PARSER;
    }

    public interface EntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string name = 1;
      /**
       * <code>optional string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>optional string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // optional bytes value = 2;
      /**
       * <code>optional bytes value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional bytes value = 2;</code>
       */
      com.google.protobuf.ByteString getValue();
    }
    /**
     * Protobuf type {@code CDOProto.Entry}
     */
    public static final class Entry extends
        com.google.protobuf.GeneratedMessage
        implements EntryOrBuilder {
      // Use Entry.newBuilder() to construct.
      private Entry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Entry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Entry defaultInstance;
      public static Entry getDefaultInstance() {
        return defaultInstance;
      }

      public Entry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Entry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder.class);
      }

      public static com.google.protobuf.Parser<Entry> PARSER =
          new com.google.protobuf.AbstractParser<Entry>() {
        public Entry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Entry(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Entry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional bytes value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString value_;
      /**
       * <code>optional bytes value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }

      private void initFields() {
        name_ = "";
        value_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, value_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CDOProto.Entry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder.class);
        }

        // Construct using com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_descriptor;
        }

        public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getDefaultInstanceForType() {
          return com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance();
        }

        public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry build() {
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry buildPartial() {
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry result = new com.cdo.google.protocol.GoogleCDO.CDOProto.Entry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cdo.google.protocol.GoogleCDO.CDOProto.Entry) {
            return mergeFrom((com.cdo.google.protocol.GoogleCDO.CDOProto.Entry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry other) {
          if (other == com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.cdo.google.protocol.GoogleCDO.CDOProto.Entry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // optional bytes value = 2;
        private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional bytes value = 2;</code>
         */
        public com.google.protobuf.ByteString getValue() {
          return value_;
        }
        /**
         * <code>optional bytes value = 2;</code>
         */
        public Builder setValue(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:CDOProto.Entry)
      }

      static {
        defaultInstance = new Entry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:CDOProto.Entry)
    }

    private int bitField0_;
    // optional sint32 level = 1;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>optional sint32 level = 1;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional sint32 level = 1;</code>
     */
    public int getLevel() {
      return level_;
    }

    // repeated .CDOProto.Entry fields = 2;
    public static final int FIELDS_FIELD_NUMBER = 2;
    private java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> fields_;
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public java.util.List<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
        getFieldsOrBuilderList() {
      return fields_;
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder getFieldsOrBuilder(
        int index) {
      return fields_.get(index);
    }

    // optional bytes clientId = 3;
    public static final int CLIENTID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString clientId_;
    /**
     * <code>optional bytes clientId = 3;</code>
     *
     * <pre>
     * Globally unique client ID 
     * </pre>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes clientId = 3;</code>
     *
     * <pre>
     * Globally unique client ID 
     * </pre>
     */
    public com.google.protobuf.ByteString getClientId() {
      return clientId_;
    }

    // optional sint32 callId = 4;
    public static final int CALLID_FIELD_NUMBER = 4;
    private int callId_;
    /**
     * <code>optional sint32 callId = 4;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    public boolean hasCallId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 callId = 4;</code>
     *
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     */
    public int getCallId() {
      return callId_;
    }

    private void initFields() {
      level_ = 0;
      fields_ = java.util.Collections.emptyList();
      clientId_ = com.google.protobuf.ByteString.EMPTY;
      callId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, level_);
      }
      for (int i = 0; i < fields_.size(); i++) {
        output.writeMessage(2, fields_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(4, callId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, level_);
      }
      for (int i = 0; i < fields_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, fields_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, clientId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, callId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cdo.google.protocol.GoogleCDO.CDOProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CDOProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cdo.google.protocol.GoogleCDO.CDOProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cdo.google.protocol.GoogleCDO.CDOProto.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Builder.class);
      }

      // Construct using com.cdo.google.protocol.GoogleCDO.CDOProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFieldsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          fieldsBuilder_.clear();
        }
        clientId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        callId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_descriptor;
      }

      public com.cdo.google.protocol.GoogleCDO.CDOProto getDefaultInstanceForType() {
        return com.cdo.google.protocol.GoogleCDO.CDOProto.getDefaultInstance();
      }

      public com.cdo.google.protocol.GoogleCDO.CDOProto build() {
        com.cdo.google.protocol.GoogleCDO.CDOProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cdo.google.protocol.GoogleCDO.CDOProto buildPartial() {
        com.cdo.google.protocol.GoogleCDO.CDOProto result = new com.cdo.google.protocol.GoogleCDO.CDOProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        if (fieldsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            fields_ = java.util.Collections.unmodifiableList(fields_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.fields_ = fields_;
        } else {
          result.fields_ = fieldsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.callId_ = callId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cdo.google.protocol.GoogleCDO.CDOProto) {
          return mergeFrom((com.cdo.google.protocol.GoogleCDO.CDOProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cdo.google.protocol.GoogleCDO.CDOProto other) {
        if (other == com.cdo.google.protocol.GoogleCDO.CDOProto.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (fieldsBuilder_ == null) {
          if (!other.fields_.isEmpty()) {
            if (fields_.isEmpty()) {
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFieldsIsMutable();
              fields_.addAll(other.fields_);
            }
            onChanged();
          }
        } else {
          if (!other.fields_.isEmpty()) {
            if (fieldsBuilder_.isEmpty()) {
              fieldsBuilder_.dispose();
              fieldsBuilder_ = null;
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000002);
              fieldsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFieldsFieldBuilder() : null;
            } else {
              fieldsBuilder_.addAllMessages(other.fields_);
            }
          }
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasCallId()) {
          setCallId(other.getCallId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cdo.google.protocol.GoogleCDO.CDOProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cdo.google.protocol.GoogleCDO.CDOProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional sint32 level = 1;
      private int level_ ;
      /**
       * <code>optional sint32 level = 1;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional sint32 level = 1;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional sint32 level = 1;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 level = 1;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        onChanged();
        return this;
      }

      // repeated .CDOProto.Entry fields = 2;
      private java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> fields_ =
        java.util.Collections.emptyList();
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = new java.util.ArrayList<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry>(fields_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder, com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> fieldsBuilder_;

      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> getFieldsList() {
        if (fieldsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fields_);
        } else {
          return fieldsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public int getFieldsCount() {
        if (fieldsBuilder_ == null) {
          return fields_.size();
        } else {
          return fieldsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getFields(int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);
        } else {
          return fieldsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder setFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.set(index, value);
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder setFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(index, value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> values) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          super.addAll(values, fields_);
          onChanged();
        } else {
          fieldsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder clearFields() {
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          fieldsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder removeFields(int index) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.remove(index);
          onChanged();
        } else {
          fieldsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder getFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder getFieldsOrBuilder(
          int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);  } else {
          return fieldsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public java.util.List<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
           getFieldsOrBuilderList() {
        if (fieldsBuilder_ != null) {
          return fieldsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fields_);
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder addFieldsBuilder() {
        return getFieldsFieldBuilder().addBuilder(
            com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder addFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().addBuilder(
            index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder> 
           getFieldsBuilderList() {
        return getFieldsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder, com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
          getFieldsFieldBuilder() {
        if (fieldsBuilder_ == null) {
          fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.cdo.google.protocol.GoogleCDO.CDOProto.Entry, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder, com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder>(
                  fields_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          fields_ = null;
        }
        return fieldsBuilder_;
      }

      // optional bytes clientId = 3;
      private com.google.protobuf.ByteString clientId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes clientId = 3;</code>
       *
       * <pre>
       * Globally unique client ID 
       * </pre>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes clientId = 3;</code>
       *
       * <pre>
       * Globally unique client ID 
       * </pre>
       */
      public com.google.protobuf.ByteString getClientId() {
        return clientId_;
      }
      /**
       * <code>optional bytes clientId = 3;</code>
       *
       * <pre>
       * Globally unique client ID 
       * </pre>
       */
      public Builder setClientId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes clientId = 3;</code>
       *
       * <pre>
       * Globally unique client ID 
       * </pre>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }

      // optional sint32 callId = 4;
      private int callId_ ;
      /**
       * <code>optional sint32 callId = 4;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public boolean hasCallId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional sint32 callId = 4;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public int getCallId() {
        return callId_;
      }
      /**
       * <code>optional sint32 callId = 4;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public Builder setCallId(int value) {
        bitField0_ |= 0x00000008;
        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 callId = 4;</code>
       *
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       */
      public Builder clearCallId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        callId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CDOProto)
    }

    static {
      defaultInstance = new CDOProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CDOProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CDOProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CDOProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CDOProto_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CDOProto_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCDO.proto\"\202\001\n\010CDOProto\022\r\n\005level\030\001 \001(\021\022" +
      "\037\n\006fields\030\002 \003(\0132\017.CDOProto.Entry\022\020\n\010clie" +
      "ntId\030\003 \001(\014\022\016\n\006callId\030\004 \001(\021\032$\n\005Entry\022\014\n\004n" +
      "ame\030\001 \001(\t\022\r\n\005value\030\002 \001(\014B&\n\027com.cdo.goog" +
      "le.protocolB\tGoogleCDOH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CDOProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CDOProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CDOProto_descriptor,
              new java.lang.String[] { "Level", "Fields", "ClientId", "CallId", });
          internal_static_CDOProto_Entry_descriptor =
            internal_static_CDOProto_descriptor.getNestedTypes().get(0);
          internal_static_CDOProto_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CDOProto_Entry_descriptor,
              new java.lang.String[] { "Name", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
