// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CDO.proto

package com.cdo.google.protocol;

public final class GoogleCDO {
  private GoogleCDO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CDOProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CDOProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional sint32 level = 1;</code>
     */
    int getLevel();

    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> 
        getFieldsList();
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getFields(int index);
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    java.util.List<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
        getFieldsOrBuilderList();
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder getFieldsOrBuilder(
        int index);

    /**
     * <pre>
     * Globally unique client ID 
     * </pre>
     *
     * <code>optional bytes clientId = 3;</code>
     */
    com.google.protobuf.ByteString getClientId();

    /**
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     *
     * <code>optional sint32 callId = 4;</code>
     */
    int getCallId();
  }
  /**
   * Protobuf type {@code CDOProto}
   */
  public  static final class CDOProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CDOProto)
      CDOProtoOrBuilder {
    // Use CDOProto.newBuilder() to construct.
    private CDOProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CDOProto() {
      level_ = 0;
      fields_ = java.util.Collections.emptyList();
      clientId_ = com.google.protobuf.ByteString.EMPTY;
      callId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CDOProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              level_ = input.readSInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                fields_ = new java.util.ArrayList<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry>();
                mutable_bitField0_ |= 0x00000002;
              }
              fields_.add(
                  input.readMessage(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.parser(), extensionRegistry));
              break;
            }
            case 26: {

              clientId_ = input.readBytes();
              break;
            }
            case 32: {

              callId_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cdo.google.protocol.GoogleCDO.CDOProto.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Builder.class);
    }

    public interface EntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CDOProto.Entry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>optional bytes value = 2;</code>
       */
      com.google.protobuf.ByteString getValue();
    }
    /**
     * Protobuf type {@code CDOProto.Entry}
     */
    public  static final class Entry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CDOProto.Entry)
        EntryOrBuilder {
      // Use Entry.newBuilder() to construct.
      private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Entry() {
        name_ = "";
        value_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Entry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {

                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString value_;
      /**
       * <code>optional bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (!value_.isEmpty()) {
          output.writeBytes(2, value_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (!value_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, value_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.cdo.google.protocol.GoogleCDO.CDOProto.Entry)) {
          return super.equals(obj);
        }
        com.cdo.google.protocol.GoogleCDO.CDOProto.Entry other = (com.cdo.google.protocol.GoogleCDO.CDOProto.Entry) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && getValue()
            .equals(other.getValue());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CDOProto.Entry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CDOProto.Entry)
          com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder.class);
        }

        // Construct using com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";

          value_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_Entry_descriptor;
        }

        public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getDefaultInstanceForType() {
          return com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance();
        }

        public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry build() {
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry buildPartial() {
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry result = new com.cdo.google.protocol.GoogleCDO.CDOProto.Entry(this);
          result.name_ = name_;
          result.value_ = value_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cdo.google.protocol.GoogleCDO.CDOProto.Entry) {
            return mergeFrom((com.cdo.google.protocol.GoogleCDO.CDOProto.Entry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry other) {
          if (other == com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
            setValue(other.getValue());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.cdo.google.protocol.GoogleCDO.CDOProto.Entry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes value = 2;</code>
         */
        public com.google.protobuf.ByteString getValue() {
          return value_;
        }
        /**
         * <code>optional bytes value = 2;</code>
         */
        public Builder setValue(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes value = 2;</code>
         */
        public Builder clearValue() {
          
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:CDOProto.Entry)
      }

      // @@protoc_insertion_point(class_scope:CDOProto.Entry)
      private static final com.cdo.google.protocol.GoogleCDO.CDOProto.Entry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.cdo.google.protocol.GoogleCDO.CDOProto.Entry();
      }

      public static com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Entry>
          PARSER = new com.google.protobuf.AbstractParser<Entry>() {
        public Entry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Entry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Entry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Entry> getParserForType() {
        return PARSER;
      }

      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>optional sint32 level = 1;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int FIELDS_FIELD_NUMBER = 2;
    private java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> fields_;
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public java.util.List<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
        getFieldsOrBuilderList() {
      return fields_;
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated .CDOProto.Entry fields = 2;</code>
     */
    public com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder getFieldsOrBuilder(
        int index) {
      return fields_.get(index);
    }

    public static final int CLIENTID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString clientId_;
    /**
     * <pre>
     * Globally unique client ID 
     * </pre>
     *
     * <code>optional bytes clientId = 3;</code>
     */
    public com.google.protobuf.ByteString getClientId() {
      return clientId_;
    }

    public static final int CALLID_FIELD_NUMBER = 4;
    private int callId_;
    /**
     * <pre>
     * a sequence number that is sent back in response
     * </pre>
     *
     * <code>optional sint32 callId = 4;</code>
     */
    public int getCallId() {
      return callId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (level_ != 0) {
        output.writeSInt32(1, level_);
      }
      for (int i = 0; i < fields_.size(); i++) {
        output.writeMessage(2, fields_.get(i));
      }
      if (!clientId_.isEmpty()) {
        output.writeBytes(3, clientId_);
      }
      if (callId_ != 0) {
        output.writeSInt32(4, callId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, level_);
      }
      for (int i = 0; i < fields_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, fields_.get(i));
      }
      if (!clientId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, clientId_);
      }
      if (callId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, callId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cdo.google.protocol.GoogleCDO.CDOProto)) {
        return super.equals(obj);
      }
      com.cdo.google.protocol.GoogleCDO.CDOProto other = (com.cdo.google.protocol.GoogleCDO.CDOProto) obj;

      boolean result = true;
      result = result && (getLevel()
          == other.getLevel());
      result = result && getFieldsList()
          .equals(other.getFieldsList());
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && (getCallId()
          == other.getCallId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      if (getFieldsCount() > 0) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + getFieldsList().hashCode();
      }
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + CALLID_FIELD_NUMBER;
      hash = (53 * hash) + getCallId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cdo.google.protocol.GoogleCDO.CDOProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cdo.google.protocol.GoogleCDO.CDOProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CDOProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CDOProto)
        com.cdo.google.protocol.GoogleCDO.CDOProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cdo.google.protocol.GoogleCDO.CDOProto.class, com.cdo.google.protocol.GoogleCDO.CDOProto.Builder.class);
      }

      // Construct using com.cdo.google.protocol.GoogleCDO.CDOProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFieldsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        level_ = 0;

        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          fieldsBuilder_.clear();
        }
        clientId_ = com.google.protobuf.ByteString.EMPTY;

        callId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cdo.google.protocol.GoogleCDO.internal_static_CDOProto_descriptor;
      }

      public com.cdo.google.protocol.GoogleCDO.CDOProto getDefaultInstanceForType() {
        return com.cdo.google.protocol.GoogleCDO.CDOProto.getDefaultInstance();
      }

      public com.cdo.google.protocol.GoogleCDO.CDOProto build() {
        com.cdo.google.protocol.GoogleCDO.CDOProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cdo.google.protocol.GoogleCDO.CDOProto buildPartial() {
        com.cdo.google.protocol.GoogleCDO.CDOProto result = new com.cdo.google.protocol.GoogleCDO.CDOProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.level_ = level_;
        if (fieldsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            fields_ = java.util.Collections.unmodifiableList(fields_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.fields_ = fields_;
        } else {
          result.fields_ = fieldsBuilder_.build();
        }
        result.clientId_ = clientId_;
        result.callId_ = callId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cdo.google.protocol.GoogleCDO.CDOProto) {
          return mergeFrom((com.cdo.google.protocol.GoogleCDO.CDOProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cdo.google.protocol.GoogleCDO.CDOProto other) {
        if (other == com.cdo.google.protocol.GoogleCDO.CDOProto.getDefaultInstance()) return this;
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (fieldsBuilder_ == null) {
          if (!other.fields_.isEmpty()) {
            if (fields_.isEmpty()) {
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFieldsIsMutable();
              fields_.addAll(other.fields_);
            }
            onChanged();
          }
        } else {
          if (!other.fields_.isEmpty()) {
            if (fieldsBuilder_.isEmpty()) {
              fieldsBuilder_.dispose();
              fieldsBuilder_ = null;
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000002);
              fieldsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFieldsFieldBuilder() : null;
            } else {
              fieldsBuilder_.addAllMessages(other.fields_);
            }
          }
        }
        if (other.getClientId() != com.google.protobuf.ByteString.EMPTY) {
          setClientId(other.getClientId());
        }
        if (other.getCallId() != 0) {
          setCallId(other.getCallId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cdo.google.protocol.GoogleCDO.CDOProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cdo.google.protocol.GoogleCDO.CDOProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int level_ ;
      /**
       * <code>optional sint32 level = 1;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional sint32 level = 1;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 level = 1;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> fields_ =
        java.util.Collections.emptyList();
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = new java.util.ArrayList<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry>(fields_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder, com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> fieldsBuilder_;

      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> getFieldsList() {
        if (fieldsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fields_);
        } else {
          return fieldsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public int getFieldsCount() {
        if (fieldsBuilder_ == null) {
          return fields_.size();
        } else {
          return fieldsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry getFields(int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);
        } else {
          return fieldsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder setFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.set(index, value);
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder setFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(com.cdo.google.protocol.GoogleCDO.CDOProto.Entry value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(index, value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addFields(
          int index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.Entry> values) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fields_);
          onChanged();
        } else {
          fieldsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder clearFields() {
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          fieldsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public Builder removeFields(int index) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.remove(index);
          onChanged();
        } else {
          fieldsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder getFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder getFieldsOrBuilder(
          int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);  } else {
          return fieldsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public java.util.List<? extends com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
           getFieldsOrBuilderList() {
        if (fieldsBuilder_ != null) {
          return fieldsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fields_);
        }
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder addFieldsBuilder() {
        return getFieldsFieldBuilder().addBuilder(
            com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder addFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().addBuilder(
            index, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .CDOProto.Entry fields = 2;</code>
       */
      public java.util.List<com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder> 
           getFieldsBuilderList() {
        return getFieldsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.cdo.google.protocol.GoogleCDO.CDOProto.Entry, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder, com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder> 
          getFieldsFieldBuilder() {
        if (fieldsBuilder_ == null) {
          fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.cdo.google.protocol.GoogleCDO.CDOProto.Entry, com.cdo.google.protocol.GoogleCDO.CDOProto.Entry.Builder, com.cdo.google.protocol.GoogleCDO.CDOProto.EntryOrBuilder>(
                  fields_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          fields_ = null;
        }
        return fieldsBuilder_;
      }

      private com.google.protobuf.ByteString clientId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Globally unique client ID 
       * </pre>
       *
       * <code>optional bytes clientId = 3;</code>
       */
      public com.google.protobuf.ByteString getClientId() {
        return clientId_;
      }
      /**
       * <pre>
       * Globally unique client ID 
       * </pre>
       *
       * <code>optional bytes clientId = 3;</code>
       */
      public Builder setClientId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Globally unique client ID 
       * </pre>
       *
       * <code>optional bytes clientId = 3;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }

      private int callId_ ;
      /**
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       *
       * <code>optional sint32 callId = 4;</code>
       */
      public int getCallId() {
        return callId_;
      }
      /**
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       *
       * <code>optional sint32 callId = 4;</code>
       */
      public Builder setCallId(int value) {
        
        callId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a sequence number that is sent back in response
       * </pre>
       *
       * <code>optional sint32 callId = 4;</code>
       */
      public Builder clearCallId() {
        
        callId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CDOProto)
    }

    // @@protoc_insertion_point(class_scope:CDOProto)
    private static final com.cdo.google.protocol.GoogleCDO.CDOProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cdo.google.protocol.GoogleCDO.CDOProto();
    }

    public static com.cdo.google.protocol.GoogleCDO.CDOProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CDOProto>
        PARSER = new com.google.protobuf.AbstractParser<CDOProto>() {
      public CDOProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CDOProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CDOProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CDOProto> getParserForType() {
      return PARSER;
    }

    public com.cdo.google.protocol.GoogleCDO.CDOProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CDOProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CDOProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CDOProto_Entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CDOProto_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCDO.proto\"\202\001\n\010CDOProto\022\r\n\005level\030\001 \001(\021\022" +
      "\037\n\006fields\030\002 \003(\0132\017.CDOProto.Entry\022\020\n\010clie" +
      "ntId\030\003 \001(\014\022\016\n\006callId\030\004 \001(\021\032$\n\005Entry\022\014\n\004n" +
      "ame\030\001 \001(\t\022\r\n\005value\030\002 \001(\014B&\n\027com.cdo.goog" +
      "le.protocolB\tGoogleCDOH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CDOProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CDOProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CDOProto_descriptor,
        new java.lang.String[] { "Level", "Fields", "ClientId", "CallId", });
    internal_static_CDOProto_Entry_descriptor =
      internal_static_CDOProto_descriptor.getNestedTypes().get(0);
    internal_static_CDOProto_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CDOProto_Entry_descriptor,
        new java.lang.String[] { "Name", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
